# Generated by Django 4.0.5 on 2022-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('sujet', models.CharField(max_length=50)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Contacts',
            },
        ),
    ]
