# Generated by Django 4.0.5 on 2022-08-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacts',
            table='Contacts',
        ),
    ]
