# Generated by Django 4.0.5 on 2022-07-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lecons',
        ),
    ]
