# Generated by Django 4.0.6 on 2022-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateNaissance',
            field=models.DateField(blank=True, max_length=1, null=True),
        ),
    ]
