# Generated by Django 4.0.5 on 2022-07-22 09:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_user_lecons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lecons',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
