# Generated by Django 4.0.6 on 2022-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
