# Generated by Django 4.0.5 on 2022-06-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
