# Generated by Django 4.0.5 on 2022-07-22 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_user_lecons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lecons',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
