# Generated by Django 4.0.5 on 2022-06-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chapitres', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Chapitres',
            },
        ),
        migrations.CreateModel(
            name='lecons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lecon', models.CharField(blank=True, max_length=255, null=True)),
                ('nbr_chapitres', models.CharField(blank=True, max_length=60, null=True)),
                ('url_photo', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'lecons',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='dateNaissance',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
