# Generated by Django 4.0.5 on 2022-06-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_chapitres_lecons_alter_user_datenaissance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitres',
            old_name='type',
            new_name='type_chapitres',
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type_Dec', models.CharField(blank=True, max_length=255, null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.chapitres')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.lecons')),
            ],
            options={
                'db_table': 'Desc',
            },
        ),
    ]
