# Generated by Django 4.0.5 on 2022-06-22 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_rename_type_chapitres_type_chapitres_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitres',
            name='url',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lecons',
            name='url_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])]),
        ),
    ]
