# Generated by Django 4.0.5 on 2022-06-24 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_chapitres_lecon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='text',
        ),
        migrations.RemoveField(
            model_name='desc',
            name='type_Dec',
        ),
        migrations.AddField(
            model_name='desc',
            name='first_dec',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desc',
            name='overview_dec',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desc',
            name='program_dec',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desc',
            name='second2_dec',
            field=models.TextField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desc',
            name='second_dec',
            field=models.TextField(default=datetime.date.today()),
            preserve_default=False,
        ),
    ]
