# Generated by Django 4.0.5 on 2022-06-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_remove_desc_text_remove_desc_type_dec_desc_first_dec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
