# Generated by Django 4.0.5 on 2022-06-30 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_user_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecons',
            name='duree',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='lecons',
            name='price',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lecons',
            name='url_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/lecons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])]),
        ),
    ]
