# Generated by Django 4.0.5 on 2022-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_lecons_duree_lecons_price_alter_lecons_url_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecons',
            name='duree',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='lecons',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
