# Generated by Django 4.0.5 on 2022-06-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_alter_lecons_duree_alter_lecons_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type_desc', models.CharField(blank=True, choices=[('1', 'Femme'), ('2', 'Homme')], max_length=1, null=True)),
                ('title_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.chapitres')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.lecons')),
            ],
            options={
                'db_table': 'Desc2',
            },
        ),
    ]
