# Generated by Django 4.0.5 on 2022-06-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_desc2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc2',
            name='type_desc',
            field=models.CharField(blank=True, choices=[('1', 'Course overview'), ('2', 'What you will learn'), ('3', 'Desc'), ('4', 'Footer desc')], max_length=1, null=True),
        ),
    ]
