# Generated by Django 4.0.5 on 2022-06-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_alter_desc2_type_desc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lecons',
            table='Lecons',
        ),
    ]
