# Generated by Django 4.0.5 on 2022-06-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_alter_desc2_chapitre'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.chapitres')),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.lecons')),
            ],
            options={
                'db_table': 'HtmlDesc',
            },
        ),
    ]
