# Generated by Django 4.0.5 on 2022-07-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_htmldesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='desc',
            name='lecon',
        ),
        migrations.RemoveField(
            model_name='desc2',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='desc2',
            name='lecon',
        ),
        migrations.RemoveField(
            model_name='htmldesc',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='htmldesc',
            name='lecon',
        ),
        migrations.DeleteModel(
            name='Chapitres',
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
        migrations.DeleteModel(
            name='Desc2',
        ),
        migrations.DeleteModel(
            name='HtmlDesc',
        ),
        migrations.DeleteModel(
            name='lecons',
        ),
    ]
