# Generated by Django 4.0.5 on 2022-08-17 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'About',
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('url_photo', models.ImageField(blank=True, null=True, upload_to='images/article/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])])),
                ('title1', models.CharField(blank=True, max_length=255, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('title2', models.CharField(blank=True, max_length=255, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('title3', models.CharField(blank=True, max_length=255, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('title4', models.CharField(blank=True, max_length=255, null=True)),
                ('description4', models.TextField(blank=True, null=True)),
                ('title5', models.CharField(blank=True, max_length=255, null=True)),
                ('description5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Chapitres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chapitres', models.CharField(blank=True, max_length=255, null=True)),
                ('type_chapitres', models.IntegerField(blank=True, choices=[(1, 'Vidéo'), (2, 'PDF')], null=True)),
                ('url', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('duree', models.CharField(blank=True, max_length=21, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Non démaré'), (1, 'Encours'), (2, 'Términé')], null=True)),
            ],
            options={
                'db_table': 'Chapitres',
            },
        ),
        migrations.CreateModel(
            name='Lecons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lecon', models.CharField(blank=True, max_length=255, null=True)),
                ('nbr_chapitres', models.CharField(blank=True, max_length=60, null=True)),
                ('url_photo', models.ImageField(blank=True, null=True, upload_to='images/lecons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])])),
                ('url_demo', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('duree', models.CharField(blank=True, max_length=21, null=True)),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'Lecons',
            },
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type_desc', models.CharField(blank=True, choices=[('1', 'Course overview'), ('2', 'What you will learn'), ('3', 'Desc'), ('4', 'Footer desc')], max_length=1, null=True)),
                ('image_or_text', models.CharField(blank=True, choices=[('1', 'Text'), ('2', 'Image')], max_length=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/description/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])])),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Learning.chapitres')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning.lecons')),
            ],
            options={
                'db_table': 'Desc',
            },
        ),
        migrations.AddField(
            model_name='chapitres',
            name='lecon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning.lecons'),
        ),
    ]
