# Generated by Django 4.0.6 on 2022-07-26 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('url_photo', models.ImageField(blank=True, null=True, upload_to='images/article/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])])),
                ('title1', models.TextField()),
                ('description1', models.TextField()),
                ('title2', models.TextField()),
                ('description2', models.TextField()),
                ('title3', models.TextField()),
                ('description3', models.TextField()),
                ('title4', models.TextField()),
                ('description4', models.TextField()),
                ('title5', models.TextField()),
                ('description5', models.TextField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
