# Generated by Django 4.0.5 on 2022-08-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description5',
            field=models.TextField(blank=b'I00\n', null=True),
        ),
    ]
