# Generated by Django 4.0.5 on 2022-08-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0002_alter_article_description5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
