# Generated by Django 4.0.5 on 2022-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0004_lecons_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecons',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
