# Generated by Django 4.0.5 on 2022-07-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitres',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='desc',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='lecons',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
