# Generated by Django 4.0.5 on 2022-07-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0006_chapitres_deleted_desc_deleted_lecons_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
