# Generated by Django 4.0.5 on 2022-07-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0007_remove_post_author_delete_comment_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desc',
            old_name='text',
            new_name='description',
        ),
    ]
